
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TOKENS_PATH = path.join(__dirname, '../src/design-tokens.json');
const GLOBALS_CSS_PATH = path.join(__dirname, '../src/globals.css');

function processTokens(obj, prefix = '--', result = []) {
    for (const key in obj) {
        if (typeof obj[key] === 'object' && obj[key] !== null) {
            // Special handling for nested "value" properties (common in token specs)
             if ('$value' in obj[key]) {
                 result.push(`${prefix}${key}: ${obj[key].$value};`);
            } else if ('value' in obj[key]) {
                result.push(`${prefix}${key}: ${obj[key].value};`);
            } else {
                processTokens(obj[key], `${prefix}${key}-`, result);
            }
        } else {
            // Direct value mapping
            result.push(`${prefix}${key}: ${obj[key]};`);
        }
    }
    return result;
}

// Specialized processing for our known Northcote structure
function generateVariables(tokens) {
    const vars = [];

    // 1. COLORS
    // Families
    Object.entries(tokens.color.families).forEach(([family, shades]) => {
        Object.entries(shades).forEach(([shade, value]) => {
            vars.push(`--color-${family}-${shade}: ${value};`);
        });
        // Add a base variable for convenience (e.g. --color-wattle-gold)
        if (shades.base) {
            vars.push(`--color-${family}: ${shades.base};`);
        }
    });

    // Semantics
    Object.entries(tokens.color.semantic).forEach(([role, data]) => {
        vars.push(`--color-${role}: ${data.value};`);
    });

    // 2. SPACING
    Object.entries(tokens.spacing).forEach(([key, data]) => {
         const val = data.$value || data.value || data;
        vars.push(`--spacing-${key}: ${val};`);
    });

    // 3. RADIUS
    Object.entries(tokens.radius).forEach(([key, data]) => {
        vars.push(`--radius-${key}: ${data.value};`);
    });

    // 4. SHADOW
    Object.entries(tokens.shadow).forEach(([key, data]) => {
        vars.push(`--shadow-${key}: ${data.value};`);
    });

    // 5. MOTION
    // Duration
    Object.entries(tokens.motion.duration).forEach(([key, value]) => {
        vars.push(`--duration-${key}: ${value};`);
    });
    // Easing
    Object.entries(tokens.motion.easing).forEach(([key, value]) => {
        vars.push(`--ease-${key}: ${value};`);
    });

    return vars;
}

const PREAMBLE = `/**
 * ═══════════════════════════════════════════════════════════════════════════
 * NORTHCOTE CURIO TYPOGRAPHY - THE FEDERATION STACK
 * Victorian Naturalist Field Station Design System V2.0
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * 🏛️ PROCLAMATION (Libre Bodoni)    — Gallery Headers, Hero Moments
 * 🌸 BLOOM       (Fraunces)         — Sub-headers, Emotional Accents
 * 📝 FIELD NOTE  (Work Sans)        — Body Text, UI Elements
 * 🔬 ANNOTATION  (JetBrains Mono)   — Laboratory Data, Technical Precision
 * 
 * ANTI-SLOP PROTOCOL: NO Inter, NO Plus Jakarta Sans, NO Roboto, NO Arial
 * ═══════════════════════════════════════════════════════════════════════════
 * Auto-generated by scripts/sync-tokens.js
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════════════════════════════════════════
 */

@import url('https://fonts.googleapis.com/css2?family=Libre+Bodoni:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,500;1,600;1,700;1,800;1,900&family=Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,100..900,0..100,0..1;1,9..144,100..900,0..100,0..1&family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=JetBrains+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap');

@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
`;

const POSTAMBLE = `
  /* Spring Physics for Hover (Viscous Breeze) */
  --spring-stiffness: 500;
  --spring-damping: 27;
}

@layer base {
  body {
    @apply bg-specimen-night text-parchment font-field-note overflow-x-hidden;
    font-variation-settings:
      'opsz' var(--leaf-opsz),
      'GRAD' var(--leaf-grad),
      'XTRA' var(--leaf-xtra);
  }

  /* ═══════════════════════════════════════════════════════════════════════
     NORTHCOTE CURIO BASE STYLES
     Enforcing the design system at the root level
     ═══════════════════════════════════════════════════════════════════════ */

  h1 {
    @apply font-proclamation text-display-lg font-bold tracking-tighter leading-none;
  }

  h2 {
    @apply font-bloom text-headline-lg font-semibold leading-tight;
  }

  h3 {
    @apply font-bloom text-headline-md font-semibold leading-snug;
  }

  h4 {
    @apply font-bloom text-headline-sm font-semibold leading-snug;
  }

  h5 {
    @apply font-field-note text-title-lg font-semibold;
  }

  h6 {
    @apply font-field-note text-title-md font-semibold;
  }

  p {
    @apply font-field-note text-body-lg text-flannel-flower;
  }

  small,
  .text-small {
    @apply font-field-note text-body-sm;
  }

  code,
  pre {
    @apply font-annotation text-label-md tracking-wider;
  }

  /* BUTTON BASE */
  button,
  .btn {
    @apply font-field-note font-semibold text-body-md transition-all duration-300 ease-viscous-breeze;
  }


  /* Dark Mode Scrollbar (M3 Expressive Aesthetic) */
  ::-webkit-scrollbar {
    width: 10px;
  }

  ::-webkit-scrollbar-track {
    background: #121212;
  }

  ::-webkit-scrollbar-thumb {
    background: #333;
    border-radius: 20px;
    border: 2px solid #121212;
    transition: background 0.3s ease;
  }

  ::-webkit-scrollbar-thumb:hover {
    background: #555;
  }
}

@layer components {
  /* ═══════════════════════════════════════════════════════════════════════
     CONTAINER COMPONENTS
     ═══════════════════════════════════════════════════════════════════════ */

  .tech-card {
    @apply bg-surface-container rounded-3xl border border-white/5 relative overflow-hidden;
    background-image: radial-gradient(rgba(255, 255, 255, 0.05) 1px, transparent 1px);
    background-size: 24px 24px;
  }

  /* ═══════════════════════════════════════════════════════════════════════
     THE PROCLAMATION (Libre Bodoni) — Gallery Headers, Hero Moments
     ═══════════════════════════════════════════════════════════════════════ */

  .text-hero,
  .text-proclamation {
    font-family: 'Libre Bodoni', 'Playfair Display', serif;
    font-weight: 700;
    font-stretch: condensed;
    letter-spacing: -0.03em;
    line-height: 110%;
    color: #F5F0E8;
    /* Parchment */
  }

  .text-proclamation-large {
    font-family: 'Libre Bodoni', 'Playfair Display', serif;
    font-weight: 900;
    font-stretch: condensed;
    letter-spacing: -0.03em;
    line-height: 100%;
    text-transform: uppercase;
  }

  /* ═══════════════════════════════════════════════════════════════════════
     THE BLOOM (Fraunces) — Sub-headers, Emotional Accents
     ═══════════════════════════════════════════════════════════════════════ */

  .text-title,
  .text-bloom {
    font-family: 'Fraunces', serif;
    font-weight: 500;
    font-variation-settings:
      'SOFT' 50,
      'WONK' 1,
      'wght' 500;
    line-height: 130%;
    color: rgba(255, 255, 255, 0.9);
  }

  /* Bloom Soft (maximum native irregularity) */
  .text-bloom-soft {
    font-family: 'Fraunces', serif;
    font-variation-settings:
      'SOFT' 100,
      'WONK' 1,
      'wght' 400;
    font-style: italic;
  }

  /* Bloom Gallery (Expressive) */
  .text-bloom-gallery {
    font-family: 'Fraunces', serif;
    font-variation-settings:
      'SOFT' 50,
      'WONK' 1,
      'wght' 700;
    color: #D4A84B;
    /* Wattle Gold */
  }

  /* Bloom Laboratory (Restrained) */
  .text-bloom-laboratory {
    font-family: 'Fraunces', serif;
    font-variation-settings:
      'SOFT' 20,
      'WONK' 0,
      'wght' 500;
  }

  /* ═══════════════════════════════════════════════════════════════════════
     THE FIELD NOTE (Work Sans) — Body Text, UI Elements
     ═══════════════════════════════════════════════════════════════════════ */

  .text-body,
  .text-field-note {
    font-family: 'Work Sans', sans-serif;
    font-weight: 400;
    line-height: 150%;
    color: rgba(255, 255, 255, 0.9);
  }

  .text-field-note-medium {
    font-family: 'Work Sans', sans-serif;
    font-weight: 500;
    line-height: 140%;
  }

  .text-field-note-bold {
    font-family: 'Work Sans', sans-serif;
    font-weight: 600;
    line-height: 140%;
  }

  /* ═══════════════════════════════════════════════════════════════════════
     THE ANNOTATION (JetBrains Mono) — Laboratory Data, Technical Precision
     ═══════════════════════════════════════════════════════════════════════ */

  .text-data,
  .text-mono,
  .text-annotation {
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-weight: 500;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    font-size: 0.75rem;
    color: rgba(255, 255, 255, 0.6);
  }

  .text-mono-large {
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    font-weight: 700;
    font-size: 3rem;
    letter-spacing: -0.02em;
  }

  /* ═══════════════════════════════════════════════════════════════════════
     BANKSIA COMPOSITION — Hero Moment Typography Duet
     ═══════════════════════════════════════════════════════════════════════ */

  .banksia-composition {
    position: relative;
    display: block;
  }

  .banksia-proclamation {
    font-family: 'Libre Bodoni', 'Playfair Display', serif;
    font-weight: 900;
    font-stretch: condensed;
    letter-spacing: -0.03em;
    line-height: 100%;
    color: #FFFFFF;
    text-transform: uppercase;
  }

  .banksia-bloom {
    font-family: 'Fraunces', serif;
    font-variation-settings:
      'SOFT' 50,
      'WONK' 1,
      'wght' 600;
    color: #D4A84B;
    /* Wattle Gold */
    transform: rotate(4deg);
    position: absolute;
    /* Positioning is context-dependent — set top/left/right per usage */
  }

  /* ═══════════════════════════════════════════════════════════════════════
     BUTTON COMPONENTS
     ═══════════════════════════════════════════════════════════════════════ */

  .btn-pebble {
    font-family: 'Work Sans', sans-serif;
    font-weight: 600;
    border-radius: 20px 20px 32px 32px;
    transition: all 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
  }

  .btn-pebble:hover {
    transform: translateY(-4px) scale(1.02);
    box-shadow: 0 16px 48px rgba(212, 168, 75, 0.4);
  }

  /* ═══════════════════════════════════════════════════════════════════════
     ANTI-SLOP VALIDATION WARNINGS
     These classes help identify forbidden fonts during development
     ═══════════════════════════════════════════════════════════════════════ */

  /* DEV ONLY: Highlight forbidden fonts */
  .debug-typography [style*="Inter"],
  .debug-typography [style*="Plus Jakarta"],
  .debug-typography [style*="Recursive"],
  .debug-typography [style*="Amstelvar"],
  .debug-typography [style*="Roboto Flex"],
  .debug-typography [style*="Arial"],
  .debug-typography [style*="Helvetica"] {
    outline: 3px dashed red !important;
  }

  .debug-typography [style*="Inter"]::after,
  .debug-typography [style*="Plus Jakarta"]::after,
  .debug-typography [style*="Recursive"]::after,
  .debug-typography [style*="Amstelvar"]::after,
  .debug-typography [style*="Roboto Flex"]::after {
    content: "❌ SLOP FONT";
    background: red;
    color: white;
    padding: 2px 4px;
    font-size: 10px;
    position: absolute;
  }
}
`;

try {
    const rawData = fs.readFileSync(TOKENS_PATH, 'utf-8');
    const tokens = JSON.parse(rawData);

    // console.log("Processing tokens...");
    const variables = generateVariables(tokens);

    // Indent variables
    const cssContent = PREAMBLE + variables.map(v => `  ${v}`).join('\n') + POSTAMBLE;

    fs.writeFileSync(GLOBALS_CSS_PATH, cssContent);
    console.log(`✅ Tokens synchronized to ${GLOBALS_CSS_PATH}`);

} catch (error) {
    console.error('❌ Error synchronizing tokens:', error);
    process.exit(1);
}
